# Generated by Django 4.2 on 2023-06-09 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bakiye',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bakiyem', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='kartlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numara', models.IntegerField(default=0, null=True)),
                ('isim', models.CharField(default=0, max_length=40, null=True)),
                ('tarih', models.CharField(max_length=6, null=True)),
                ('guvenlik_kodu', models.CharField(max_length=4, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='kod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kodum', models.CharField(default=0, max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isim', models.CharField(max_length=100)),
                ('resim', models.ImageField(upload_to='urun_resimleri/')),
                ('sayi', models.IntegerField()),
                ('fiyat', models.DecimalField(decimal_places=2, max_digits=8)),
                ('kargo_bedeli', models.IntegerField()),
            ],
        ),
    ]
