# Generated by Django 4.2 on 2023-06-08 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopie', '0005_alter_user_options_alter_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
